version: '3.7'
services:
  questionable_postgres:
    container_name: questionable_postgres
    image: postgres:alpine
    ports:
      - 5442:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      TZ: America/Sao_Paulo
    volumes:
      - ./postgresql_service/postgresql:/var/lib/postgresql
      - ./postgresql_service/setup:/docker-entrypoint-initdb.d
  questionable_node:
    container_name: questionable_node
    build: ./node_service
    depends_on:
      - questionable_postgres
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: questionable_postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PORT: ${POSTGRES_PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      TZ: America/Sao_Paulo
